program AquelooSIGA;



{$R *.dres}

uses
  Forms,
  SysUtils,
  unPrincipal in 'unPrincipal.pas' {FmPrincipal},
  undmPrincipal in 'datamodules\undmPrincipal.pas' {dmPrincipal: TDataModule},
  DCConfiguration in 'log4delphi\DCConfiguration.pas',
  log4fpc in 'log4delphi\log4fpc.pas',
  TAppenderUnit in 'log4delphi\TAppenderUnit.pas',
  TBDELogInserterUnit in 'log4delphi\TBDELogInserterUnit.pas',
  TConfiguratorUnit in 'log4delphi\TConfiguratorUnit.pas',
  TDBAppenderUnit in 'log4delphi\TDBAppenderUnit.pas',
  TDBLogInserterUnit in 'log4delphi\TDBLogInserterUnit.pas',
  TDBXLogInserterUnit in 'log4delphi\TDBXLogInserterUnit.pas',
  TErrorHandlerUnit in 'log4delphi\TErrorHandlerUnit.pas',
  TFileAppenderUnit in 'log4delphi\TFileAppenderUnit.pas',
  THTMLLayoutUnit in 'log4delphi\THTMLLayoutUnit.pas',
  TIBXLogInserterUnit in 'log4delphi\TIBXLogInserterUnit.pas',
  TIniConfiguratorUnit in 'log4delphi\TIniConfiguratorUnit.pas',
  TLayoutUnit in 'log4delphi\TLayoutUnit.pas',
  TLevelUnit in 'log4delphi\TLevelUnit.pas',
  TLoggerUnit in 'log4delphi\TLoggerUnit.pas',
  TLoggingEventUnit in 'log4delphi\TLoggingEventUnit.pas',
  TLogLogUnit in 'log4delphi\TLogLogUnit.pas',
  TNullAppenderUnit in 'log4delphi\TNullAppenderUnit.pas',
  TOnlyOnceErrorHandlerUnit in 'log4delphi\TOnlyOnceErrorHandlerUnit.pas',
  TOptionConverterUnit in 'log4delphi\TOptionConverterUnit.pas',
  TPatternLayoutUnit in 'log4delphi\TPatternLayoutUnit.pas',
  TPrintWriterUnit in 'log4delphi\TPrintWriterUnit.pas',
  TPropertiesUnit in 'log4delphi\TPropertiesUnit.pas',
  TPropertyConfiguratorUnit in 'log4delphi\TPropertyConfiguratorUnit.pas',
  TRollingFileAppenderUnit in 'log4delphi\TRollingFileAppenderUnit.pas',
  TSimpleLayoutUnit in 'log4delphi\TSimpleLayoutUnit.pas',
  TStringUnit in 'log4delphi\TStringUnit.pas',
  TWriterAppenderUnit in 'log4delphi\TWriterAppenderUnit.pas',
  TXMLLayoutUnit in 'log4delphi\TXMLLayoutUnit.pas',
  TConsoleUnit in 'log4delphi\TConsoleUnit.pas' {TConsole},
  unAplEnviaEmail in 'unAplEnviaEmail.pas' {fmAplEnviaEmail},
  unCadUsuarioAlteraSenha in 'unCadUsuarioAlteraSenha.pas' {fmCadUsuarioAlteraSenha},
  unCadDocumento in 'unCadDocumento.pas' {fmCadDocumento},
  unAplVisualizaImagem in 'unAplVisualizaImagem.pas' {fmAplVisualizaImagem},
  unCadImagem in 'unCadImagem.pas' {fmCadImagem},
  unCadPerfil in 'unCadPerfil.pas' {fmCadPerfil},
  UnAplExportaXLS in 'UnAplExportaXLS.pas',
  unConFiltroPadrao in 'unConFiltroPadrao.pas' {fmConFiltroPadrao},
  unConFiltroMaterial in 'unConFiltroMaterial.pas' {fmConFiltroMaterial},
  unCadUsuario in 'unCadUsuario.pas' {fmCadUsuario},
  unCadTipoMovimento in 'unCadTipoMovimento.pas' {fmCadTipoMovimento},
  unCadFormaPagamento in 'unCadFormaPagamento.pas' {fmCadFormaPagamento},
  unCadFornecedor in 'unCadFornecedor.pas' {fmCadFornecedor},
  unCadMotivoUrgencia in 'unCadMotivoUrgencia.pas' {fmCadMotivoUrgencia},
  unCadMarca in 'unCadMarca.pas' {fmCadMarca},
  unCadModelo in 'unCadModelo.pas' {fmCadModelo},
  unCadPais in 'unCadPais.pas' {fmCadPais},
  unCadUF in 'unCadUF.pas' {fmCadUF},
  unCadLocalidade in 'unCadLocalidade.pas' {fmCadLocalidade},
  unCadEmbalagem in 'unCadEmbalagem.pas' {fmCadEmbalagem},
  unCadBairro in 'unCadBairro.pas' {fmCadBairro},
  unCadCEP in 'unCadCEP.pas' {fmCadCEP},
  unCadLogradouro in 'unCadLogradouro.pas' {fmCadLogradouro},
  unCadFamilia in 'unCadFamilia.pas' {fmCadFamilia},
  unCadMaterial in 'unCadMaterial.pas' {fmCadMaterial},
  unConAquisicao in 'unConAquisicao.pas' {fmConAquisicao},
  unConAquisicaoItens in 'unConAquisicaoItens.pas' {fmConAquisicaoItens},
  unCadAquisicao in 'unCadAquisicao.pas' {fmCadAquisicao},
  unConAquisicaoParcelasPendentes in 'unConAquisicaoParcelasPendentes.pas' {fmConAquisicaoParcelasPendentes},
  unConAquisicaoEntregasPendentes in 'unConAquisicaoEntregasPendentes.pas' {fmConAquisicaoEntregasPendentes},
  unAplOrdenaGrid in 'unAplOrdenaGrid.pas' {fmAplOrdenaGrid},
  unRelHistoricoAquisicaoParcela in 'unRelHistoricoAquisicaoParcela.pas' {fmRelHistoricoAquisicaoParcela},
  unRelHistoricoMovimento in 'unRelHistoricoMovimento.pas' {fmRelHistoricoMovimento},
  unCadLimiteFinanceiro in 'unCadLimiteFinanceiro.pas' {fmCadLimiteFinanceiro},
  unCadAquisicaoParcela in 'unCadAquisicaoParcela.pas' {fmCadAquisicaoParcela},
  unCadReceita in 'unCadReceita.pas' {fmCadReceita},
  unAplEditaTexto in 'unAplEditaTexto.pas' {fmAplEditaTexto},
  unCadDespesaConfiguracao in 'unCadDespesaConfiguracao.pas' {fmCadDespesaConfiguracao},
  unCadDespesa in 'unCadDespesa.pas' {fmCadDespesa},
  unConDespesaItensPendentes in 'unConDespesaItensPendentes.pas' {fmConDespesaItensPendentes},
  unConMovimentacao in 'unConMovimentacao.pas' {fmConMovimentacao},
  unRelHistoricoMaterialGarantia in 'unRelHistoricoMaterialGarantia.pas' {fmRelHistoricoMaterialGarantia},
  unConDocumento in 'unConDocumento.pas' {fmConDocumento},
  unRelHistoricoMaterialFornecedor in 'unRelHistoricoMaterialFornecedor.pas' {fmRelHistoricoMaterialFornecedor},
  unAplValidaAcesso in 'unAplValidaAcesso.pas' {fmAplValidaAcesso},
  undmEstilo in 'Datamodules\undmEstilo.pas' {dmEstilo: TDataModule},
  unCadAquisicaoItem in 'unCadAquisicaoItem.pas' {fmAquisicaoItem},
  unCadInvestimento in 'unCadInvestimento.pas' {fmCadInvestimento},
  unCadInvestimentoLimite in 'unCadInvestimentoLimite.pas' {fmCadInvestimentoLimite},
  unCadReceitaConfiguracao in 'unCadReceitaConfiguracao.pas' {fmCadReceitaConfiguracao},
  unRelHistoricoCombustivel in 'unRelHistoricoCombustivel.pas' {fmRelHistoricoCombustivel},
  unCadInvestimentoSaqueParcial in 'unCadInvestimentoSaqueParcial.pas' {fmCadInvestimentoSaqueParcial},
  unCriptografia in 'classes\unCriptografia.pas',
  unGeral in 'classes\unGeral.pas',
  unInformacaoGeografica in 'classes\unInformacaoGeografica.pas',
  unManipulaXML in 'classes\unManipulaXML.pas',
  unPais in 'classes\unPais.pas',
  unParametro in 'classes\unParametro.pas',
  unUnidadeFederacao in 'classes\unUnidadeFederacao.pas',
  unLocalidade in 'classes\unLocalidade.pas',
  unLogradouro in 'classes\unLogradouro.pas',
  unBairro in 'classes\unBairro.pas',
  unCEP in 'classes\unCEP.pas',
  unSujeito in 'classes\unSujeito.pas',
  unUsuario in 'classes\unUsuario.pas',
  unFornecedor in 'classes\unFornecedor.pas',
  unCadastroBasico in 'classes\unCadastroBasico.pas',
  unPerfil in 'classes\unPerfil.pas',
  unMotivoUrgencia in 'classes\unMotivoUrgencia.pas',
  unFormaPagamento in 'classes\unFormaPagamento.pas',
  unTipoMovimento in 'classes\unTipoMovimento.pas',
  unCatalogo in 'classes\unCatalogo.pas',
  unFamilia in 'classes\unFamilia.pas',
  unMarca in 'classes\unMarca.pas',
  unModelo in 'classes\unModelo.pas',
  unEmbalagem in 'classes\unEmbalagem.pas',
  unMaterial in 'classes\unMaterial.pas',
  unDocumento in 'classes\unDocumento.pas',
  unInvestimento in 'classes\unInvestimento.pas',
  unAquisicao in 'classes\unAquisicao.pas',
  unDespesa in 'classes\unDespesa.pas',
  unReceita in 'classes\unReceita.pas',
  unResSearch in 'classes\unResSearch.pas',
  unAplConfiguracoes in 'unAplConfiguracoes.pas' {fmAplConfiguracoes},
  unAplInicializa in 'unAplInicializa.pas' {fmAplInicializa};

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.Title := 'Aqueloo - SIGA';
  TConfiguratorUnit.doPropertiesConfiguration(ExtractFileDir(Application.ExeName) + '\log4delphi.properties');
  Application.CreateForm(TfmPrincipal, fmPrincipal);
  Application.Run;
end.
